"""initial migration

Revision ID: 7f693f7978d8
Revises: 
Create Date: 2026-05-01 13:22:31.121563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f693f7978d8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aerolineas',
    sa.Column('id_aerolinea', sa.Integer(), nullable=False),
    sa.Column('nombre_aerolinea', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_aerolinea')
    )
    op.create_index(op.f('ix_aerolineas_id_aerolinea'), 'aerolineas', ['id_aerolinea'], unique=False)
    op.create_table('aeropuertos',
    sa.Column('id_aeropuerto', sa.Integer(), nullable=False),
    sa.Column('nombre_aeropuerto', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_aeropuerto')
    )
    op.create_index(op.f('ix_aeropuertos_id_aeropuerto'), 'aeropuertos', ['id_aeropuerto'], unique=False)
    op.create_table('movimientos',
    sa.Column('id_movimiento', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_movimiento')
    )
    op.create_index(op.f('ix_movimientos_id_movimiento'), 'movimientos', ['id_movimiento'], unique=False)
    op.create_table('vuelos',
    sa.Column('id_vuelo', sa.Integer(), nullable=False),
    sa.Column('id_aerolinea', sa.Integer(), nullable=False),
    sa.Column('id_aeropuerto', sa.Integer(), nullable=False),
    sa.Column('id_movimiento', sa.Integer(), nullable=False),
    sa.Column('dia', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['id_aerolinea'], ['aerolineas.id_aerolinea'], ),
    sa.ForeignKeyConstraint(['id_aeropuerto'], ['aeropuertos.id_aeropuerto'], ),
    sa.ForeignKeyConstraint(['id_movimiento'], ['movimientos.id_movimiento'], ),
    sa.PrimaryKeyConstraint('id_vuelo')
    )
    op.create_index(op.f('ix_vuelos_id_vuelo'), 'vuelos', ['id_vuelo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vuelos_id_vuelo'), table_name='vuelos')
    op.drop_table('vuelos')
    op.drop_index(op.f('ix_movimientos_id_movimiento'), table_name='movimientos')
    op.drop_table('movimientos')
    op.drop_index(op.f('ix_aeropuertos_id_aeropuerto'), table_name='aeropuertos')
    op.drop_table('aeropuertos')
    op.drop_index(op.f('ix_aerolineas_id_aerolinea'), table_name='aerolineas')
    op.drop_table('aerolineas')
    # ### end Alembic commands ###
